#!/usr/bin/env python3
"""
Scan command_line directories and generate executable mappings
for LIBTBX_SET_DISPATCHER_NAME directives
"""
import os
import re
from pathlib import Path

def find_dispatcher_names(python_file):
    """Extract all LIBTBX_SET_DISPATCHER_NAME directives from a Python file"""
    names = []
    try:
        with open(python_file, 'r') as f:
            for line in f:
                match = re.search(r'#\s*LIBTBX_SET_DISPATCHER_NAME\s+(\S+)', line)
                if match:
                    names.append(match.group(1))
    except:
        pass
    return names

def infer_executable_name(py_file, module_name):
    """Infer executable name from file path if not explicitly set"""
    # Remove .py extension
    base_name = py_file.stem

    # Special case mappings for modules with different naming conventions
    # boost_adaptbx commands are exposed as "boost.*"
    if module_name == 'boost_adaptbx' and base_name in ['gcd', 'lcm']:
        return f"boost.{base_name}"

    # Handle files with dots in the name (e.g., eltbx.show_fp_fdp.py, cif.validate.py)
    # These should keep their dots as-is, just prepend module name
    if '.' in base_name:
        return f"{module_name}.{base_name}"

    # Default: module.filename (keep underscores as underscores)
    # The convention is that the Python file name becomes the command name
    return f"{module_name}.{base_name}"

def scan_command_line_dirs(base_dir, auto_discover=True):
    """Scan all command_line directories for executable scripts"""
    executables = {}
    base_path = Path(base_dir)

    # Find all command_line directories
    for command_line_dir in base_path.glob('*/command_line'):
        module_name = command_line_dir.parent.name

        # Scan Python files
        for py_file in command_line_dir.glob('*.py'):
            if py_file.name == '__init__.py':
                continue

            dispatcher_names = find_dispatcher_names(py_file)
            if dispatcher_names:
                rel_path = py_file.relative_to(base_path)
                for dispatcher_name in dispatcher_names:
                    executables[dispatcher_name] = str(rel_path)
            elif auto_discover:
                # Infer executable name
                inferred_name = infer_executable_name(py_file, module_name)
                rel_path = py_file.relative_to(base_path)
                executables[inferred_name] = str(rel_path)

        # Scan shell scripts (.sh and .csh files)
        for script_file in list(command_line_dir.glob('*.sh')) + list(command_line_dir.glob('*.csh')):
            # For shell scripts, use the filename without extension
            base_name = script_file.stem
            script_name = f"{module_name}.{base_name}"
            rel_path = script_file.relative_to(base_path)
            executables[script_name] = str(rel_path)

    return executables

def generate_cmake_content(executables, filter_list=None):
    """Generate CMakeLists.txt content for executables"""
    lines = [
        "# Auto-generated executable targets",
        "# Generated by generate_executables.py",
        ""
    ]

    # Filter if requested
    if filter_list:
        filter_set = set(filter_list)
        executables = {k: v for k, v in executables.items() if k in filter_set}
        missing = filter_set - set(executables.keys())
        if missing:
            lines.append(f"# WARNING: {len(missing)} executables not found")
            for name in sorted(missing):
                lines.append(f"# MISSING: {name}")
            lines.append("")

    for exe_name in sorted(executables.keys()):
        script_path = executables[exe_name]
        lines.append(f'add_python_executable({exe_name} "${{CMAKE_SOURCE_DIR}}/{script_path}")')

    return '\n'.join(lines)

if __name__ == '__main__':
    import sys

    # Use current directory or provided path
    base_dir = sys.argv[1] if len(sys.argv) > 1 else '.'

    # Check for filter file
    filter_list = None
    if len(sys.argv) > 2:
        filter_file = sys.argv[2]
        if os.path.exists(filter_file):
            with open(filter_file, 'r') as f:
                filter_list = [line.strip() for line in f if line.strip() and not line.startswith('#')]
            print(f"Using filter list from {filter_file} ({len(filter_list)} executables)")

    print(f"Scanning {base_dir} for executable scripts...")
    executables = scan_command_line_dirs(base_dir)

    print(f"Found {len(executables)} executables total")

    # Generate CMakeLists.txt content
    cmake_content = generate_cmake_content(executables, filter_list)

    output_file = 'executables.cmake'
    with open(output_file, 'w') as f:
        f.write(cmake_content)

    print(f"\nGenerated {output_file}")
    if filter_list:
        print(f"Included {len([k for k in executables.keys() if k in filter_list])} filtered executables")

    print(f"\nAdd this line to your main CMakeLists.txt:")
    print(f"  include(executables.cmake)")

